# .gitpod.yml - Configuration for Gitpod Cloud Development Environment

tasks:
  - name: Setup and Launch Drupal
    init: |
      # This runs only on the first start to prepare the environment
      echo "--- Preparing environment ---"
      docker compose up -d
      sleep 15
      echo "--- Installing base dependencies with Composer ---"
      docker compose exec -T drupal composer install
      echo "--- Installing Drupal ---"
      docker compose exec -T drupal /opt/drupal/vendor/bin/drush site:install minimal --db-url="mysql://user:pass@db:3306/drupal" --site-name="Lending Library Test" --account-name=admin --account-pass=admin -y
      echo "--- Downloading module dependencies ---"
      docker compose exec -T drupal composer require drupal/eck
      echo "--- Enabling the Lending Library module ---"
      docker compose exec -T drupal /opt/drupal/vendor/bin/drush en lending_library -y
      echo "--- Clearing caches ---"
      docker compose exec -T drupal /opt/drupal/vendor/bin/drush cr
      echo "--- Setup complete! Site is ready. ---"
    command: |
      # This runs every time the workspace starts
      docker compose start

# Define which ports to expose and what to do with them
ports:
  - port: 8080
    onOpen: open-preview # Automatically open the Drupal site in a browser tab
  - port: 3306
    onOpen: ignore