# .gitpod.yml
tasks:
  - name: Setup Drupal + ECK (no custom module)
    init: |
      bash scripts/gitpod-init.sh
    command: |
      docker compose start

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
