# .gitpod.yml
tasks:
  - name: Setup and Launch Drupal
    init: |
      echo "--- Preparing environment ---"
      docker compose up -d
      # Give DB a moment to initialize
      sleep 15

      echo "--- Install Composer in container ---"
      docker compose exec -T drupal bash -lc 'apt-get update && apt-get install -y curl git unzip && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && composer --version'

      echo "--- Create Drupal project (composer) ---"
      docker compose exec -T drupal bash -lc 'mkdir -p /opt/drupal && [ -f /opt/drupal/composer.json ] || composer create-project drupal/recommended-project:^10.3 /opt/drupal'

      echo "--- Point Apache docroot at /opt/drupal/web ---"
      docker compose exec -T drupal bash -lc 'rm -rf /var/www/html && ln -s /opt/drupal/web /var/www/html'

      echo "--- Symlink this repo as a custom module ---"
      docker compose exec -T drupal bash -lc 'mkdir -p /opt/drupal/web/modules/custom && ln -sfn /opt/project /opt/drupal/web/modules/custom/lending_library'

      echo "--- Require Drush and module deps ---"
      docker compose exec -T drupal bash -lc 'cd /opt/drupal && composer require drush/drush:^13 drupal/eck -W'

      echo "--- Install Drupal site ---"
      docker compose exec -T drupal bash -lc "/opt/drupal/vendor/bin/drush si standard \
        --db-url='mysql://user:pass@db:3306/drupal' \
        --site-name='Lending Library Test' \
        --account-name=admin --account-pass=admin -y"

      echo "--- Enable your module ---"
      docker compose exec -T drupal bash -lc '/opt/drupal/vendor/bin/drush en lending_library -y'

      echo "--- Set file permissions ---"
      docker compose exec -T drupal bash -lc 'chown -R www-data:www-data /opt/drupal/web/sites/default/files || true'

      echo "--- Setup complete ---"
    command: |
      # Runs on each workspace start (keeps containers running)
      docker compose start

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
