tasks:
  - name: Setup
    before: |
      git config --global --add safe.directory /opt/drupal
    init: |
      bash scripts/gitpod-init.sh
    command: |
      docker compose start

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore