# docker-compose.yml
services:
  drupal:
    image: drupal:10-php8.2-apache
    volumes:
      - ./:/opt/drupal
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mariadb:10.4.17
    environment:
      MYSQL_DATABASE: drupal10
      MYSQL_USER: drupal10
      MYSQL_PASSWORD: drupal10
      MYSQL_ROOT_PASSWORD: root_password