# docker-compose.yml
version: "3.8"

services:
  drupal:
    image: drupal:10-php8.2-apache
    working_dir: /opt/drupal
    volumes:
      - ./:/opt/drupal/web/modules/custom/lending_library
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.4.17
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root_password